version: 2.1

jobs:
  build-macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: ./scripts/build.sh
  build-ubuntu:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: ./scripts/build.sh


workflows:
  all-tests:
    jobs:
      - build-macos
      - build-ubuntu